package ru.example.itemhotkeys;

public enum ActionStage {
    /*
     * Этапы Ливалки, Ловушки и Эндер-ловушки.
     */
    REGULAR_VERIFY_HOTBAR,
    REGULAR_WAIT_AFTER_SLOT_SELECT,
    REGULAR_USE_ITEM,
    REGULAR_WAIT_AFTER_USE,
    REGULAR_RESTORE_SELECTED_SLOT,
    REGULAR_WAIT_AFTER_SLOT_RESTORE,
    REGULAR_RESTORE_INVENTORY,
    REGULAR_WAIT_AFTER_INVENTORY_RESTORE,
    REGULAR_VERIFY_RESTORE,

    /*
     * Этапы Анти-Флая.
     */
    ANTI_FLY_VERIFY_OFFHAND,
    ANTI_FLY_WAIT_BEFORE_SNEAK,
    ANTI_FLY_PRESS_SNEAK,
    ANTI_FLY_HOLD_SNEAK,
    ANTI_FLY_RELEASE_SNEAK,
    ANTI_FLY_WAIT_FOR_SERVER_CONFIRMATION,
    ANTI_FLY_RESTORE_OFFHAND,
    ANTI_FLY_WAIT_AFTER_RESTORE,
    ANTI_FLY_VERIFY_RESTORE,

    FINISH
}
